### ISSUE TITLE
how do you manage extra tag like "lifecycle" ?

### ISSUE THREAD

**Issue by aversag** [claranet/terraform-azurerm-redis#2]
if I put 

  lifecycle {
    prevent_destroy = true
  }

I got this :

│ Error: Reserved block type name in module block
│
│   on redis.tf line 24, in module "redis":
│   24:   lifecycle {
│
│ The block type name "lifecycle" is reserved for use by Terraform in a future version.

**Comment by jmapro** [comment]
Terraform does not allow to use lifecycle in module blocks. If you want to protect the resource from deletion, I suggest you to use locks https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_lock

**Comment by aversag** [comment]
thank you for the quick answer :)
